### ISSUE TITLE
Spago migrate some missing parts

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1053]
spago.dhall
```dhall
{ name = "myproject"
, dependencies =
  [ "aff"
  , "argonaut-aeson-generic"
  , "argonaut-codecs"
  , "argonaut-core"
  , "argonaut-generic"
  , "arrays"
  , "arrays-extra"
  , "assert"
  , "console"
  , "const"
  , "datetime"
  , "debug"
  , "dom-indexed"
  , "effect"
  , "either"
  , "enums"
  , "exceptions"
  , "filterable"
  , "foldable-traversable"
  , "foreign"
  , "foreign-object"
  , "halogen"
  , "halogen-hooks"
  , "halogen-portal"
  , "halogen-store"
  , "halogen-subscriptions"
  , "integers"
  , "js-bigints"
  , "js-date"
  , "lists"
  , "maybe"
  , "monad-loops"
  , "newtype"
  , "now"
  , "numbers"
  , "optparse"
  , "ordered-collections"
  , "ordered-set"
  , "partial"
  , "prelude"
  , "record"
  , "refs"
  , "routing"
  , "routing-duplex"
  , "strings"
  , "strings-extra"
  , "stringutils"
  , "tailrec"
  , "transformers"
  , "tuples"
  , "typelevel-prelude"
  , "unfoldable"
  , "unordered-collections"
  , "unsafe-coerce"
  , "web-dom"
  , "web-events"
  , "web-html"
  , "web-socket"
  , "web-storage"
  , "web-uievents"
  ]
, packages = ./packages.dhall
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
}
```

packages.dhall
```dhall
-}
let upstream =
      https://github.com/purescript/package-sets/releases/download/psc-0.15.10-20231007/packages.dhall
        sha256:f6873e62706e0451b8ec115572e881350043716d597589e3d868731752baf200

let overrides =
      { halogen-store = ./purescript-halogen-store/spago.dhall as Location
      , datetime = ./purescript-datetime/spago.dhall as Location
      , halogen-portal =
        { repo =
            "https://github.com/thomashoneyman/purescript-halogen-portal.git"
        , version = "main"
        , dependencies =
          [ "aff"
          , "avar"
          , "console"
          , "effect"
          , "foldable-traversable"
          , "free"
          , "halogen"
          , "halogen-subscriptions"
          , "maybe"
          , "prelude"
          , "tailrec"
          , "transformers"
          , "typelevel-prelude"
          , "web-html"
          ]
        }
      , optparse = ./purescript-optparse/spago.dhall as Location
      }

let additions = {=}

in  upstream // overrides // additions
```

spago.yaml
```yaml
package:
  dependencies:
  - aff
  - argonaut-aeson-generic
  - argonaut-codecs
  - argonaut-core
  - argonaut-generic
  - arrays
  - arrays-extra
  - assert
  - console
  - const
  - datetime
  - debug
  - dom-indexed
  - effect
  - either
  - enums
  - exceptions
  - filterable
  - foldable-traversable
  - foreign
  - foreign-object
  - halogen
  - halogen-hooks
  - halogen-portal
  - halogen-store
  - halogen-subscriptions
  - integers
  - js-bigints
  - js-date
  - lists
  - maybe
  - monad-loops
  - newtype
  - now
  - numbers
  - optparse
  - ordered-collections
  - ordered-set
  - partial
  - prelude
  - record
  - refs
  - routing
  - routing-duplex
  - strings
  - strings-extra
  - stringutils
  - tailrec
  - transformers
  - tuples
  - typelevel-prelude
  - unfoldable
  - unordered-collections
  - unsafe-coerce
  - web-dom
  - web-events
  - web-html
  - web-socket
  - web-storage
  - web-uievents
  name: myproject
workspace:
  extra_packages:
    halogen-portal:
      dependencies:
      - aff
      - avar
      - console
      - effect
      - foldable-traversable
      - free
      - halogen
      - halogen-subscriptions
      - maybe
      - prelude
      - tailrec
      - transformers
      - typelevel-prelude
      - web-html
      git: https://github.com/thomashoneyman/purescript-halogen-portal.git
      ref: main
  package_set:
    url: https://raw.githubusercontent.com/purescript/package-sets/psc-0.15.10-20231007/packages.json
```

1.
This is missing from the yaml
```
      { halogen-store = ./purescript-halogen-store/spago.dhall as Location
      , datetime = ./purescript-datetime/spago.dhall as Location
...snip
      , optparse = ./purescript-optparse/spago.dhall as Location
```

2.
This is missing from the yaml
```
, sources = [ "src/**/*.purs", "test/**/*.purs" ]
```

3.
Would be nice if the project name goes before it's dependencies like in dhall
