### ISSUE TITLE
Simplify PSA option of warning censoring to 'all', list of codes to censor, and list of messages to censor via prefix test

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1067]
I propose we refactor the PSA warning censoring options to one of these two values:
```yaml
censor_warnings:
  # Case 1: a string
  "all"

  # Case 2: an object where one of these keys is optional
  censor_by_code:
    - CodeName1
    - CodeName2
  
  censor_by_prefix:
    - "\"Data.Map\"'s `Semigroup` instance" 
```

**Comment by JordanMartinez** [comment]
For some history: https://github.com/natefaubion/purescript-psa/pull/45

**Comment by f-f** [comment]
Yep, this is great.

An alternative syntax could be:
- either `censor_warnings: all`
- or a list of items
  ```yaml
  censor_warnings:
    - CodeName1 # If it's a string then it's a warning code
    # if it's an object with `by_prefix` then we censor by prefix
    # the ">" is yaml syntax for block-string, see https://yaml-multiline.info/
    - by_prefix: >
        "Data.Map"'s `Semigroup` instance
  ```
