### ISSUE TITLE
Registry package name limitations are also applied to local packages

### ISSUE THREAD

**Issue by finnhodgkin** [purescript/spago#1086]
Legacy spago didn't have length validation on local package names, whereas spago@next has a strict 50-character limit.

Unfortunately in the project I'm migrating we have a bunch of generated libraries with really long names like `oa-gql-enums-author-field-response-versions-select-column`. It wouldn't be the end of the world if we had to cut the names down or merge the generated libraries, but it feels like an arbitrary limit for unpublished local packages.

Seems to be caused by the spago.yaml being read using the parser from registry-dev:

[Spago config parser](https://github.com/purescript/spago/blob/master/core/src/Config.purs#L85C28)

[Registry name parser](https://github.com/purescript/registry-dev/blob/master/lib/src/PackageName.purs#L119)

Other than this the migration was going great, I'm really loving the new workspace features! 🎉 

Minimal example:

```
package:
  dependencies:
    - console
    - prelude
  name: a-really-long-package-name-that-is-53-characters-long
  test:
    dependencies: []
    main: Test.Main
workspace:
  extra_packages: {}
  package_set:
    registry: 43.0.0
```

Results in: 

> Reading Spago workspace configuration...
\
❌ Couldn't parse Spago config, error:
  An error occurred while decoding a JSON value:
  Under 'Config':
  At object key package:
  Under 'PackageConfig':
  At object key name:
  Under 'PackageName':
  Unexpected value "a-really-long-package-name-that-is-53-characters-long".
Run `spago init` to initialise a new project.
