### ISSUE TITLE
Trouble using local package_set

### ISSUE THREAD

**Issue by jeslie0** [purescript/spago#1088]
I don't seem to be able to use local package sets with spago-0.93.14. I have run `spago init` and changed my `spago.yaml` to the following:

```yaml
package:
  dependencies:
    - console
    - effect
    - prelude
  name: test
  test:
    dependencies: []
    main: Test.Main
workspace:
  extra_packages: {}
  package_set:
    path: ./packages.json
```

Running `spago build` presents me with the following error:
```
❌ Couldn't parse Spago config, error:
  An error occurred while decoding a JSON value:
  Under 'Config':
  At object key workspace:
  Under 'WorkspaceConfig':
  At object key package_set:
  Under 'SetFromUrl':
  At object key url:
  No value was found.
```

Are local package sets allowed? The [custom-package-sets](https://github.com/purescript/spago#custom-package-sets) seems to imply that this is allowed, but it isn't mentioned in the [workspace](https://github.com/purescript/spago#the-workspace) section at all.
