### ISSUE TITLE
Allow bundling of multiple files per package

### ISSUE THREAD

**Issue by Anteproperispomenon** [purescript/spago#1135]
At the moment, you can only specify one file to bundle per package in a `spago.yaml` file. This can be a pain if you have one project with multiple main modules you want to bundle into separate `.js` files. While you could create a separate sub-project for each `Main` and bundle them separately, it could be useful to have a command that would bundle multiple `Main`s at once. This would be especially useful if we could invoke `esbuild` with options to improve bundling of multiple outputs at once.

In order to maintain backwards-compatibility, I'd suggest keeping one "main" bundle target, but then allow an optional list of "extra" bundle targets. e.g.

```purescript
type SubBundleOptions =
  { minify :: Boolean
  , name :: String -- To allow bundling one file at a time, if requested.
  , sourceMaps :: Boolean
  , module :: String
  , outfile :: FilePath
  , platform :: BundlePlatform
  , type :: BundleType
  , extraArgs :: Array String
  }

type BundleOptions =
  { minify :: Boolean
  , sourceMaps :: Boolean
  , module :: String
  , name :: String -- Might not be necessary here.
  , outfile :: FilePath
  , platform :: BundlePlatform
  , type :: BundleType
  , subBundles :: Array SubBundleOptions
  , extraArgs :: Array String
  }
```

Where the default values (aside from `name`) of each sub-bundle are taken from the main bundle (we could even make `SubBundleOptions` recursive, to allow a tree-like structure, but that might be overkill). The `name` field would allow you to specify one (or possibly more) output(s) to bundle when running `spago bundle` from the console. e.g.

```console
spago bundle -p package-name --name app1
```

As an example of what this could look like...

```yaml
bundle:
  name: "app1"
  module: Main
  outfile: "app/main-app.js"
  platform: browser
  type: "app"
  sub_bundles:
    - name: "app2"
      module: MainAlt1
      outfile: "app/alt-app1.js"
    - name: "app3"      
      module: MainAlt2
      outfile: "app/alt-app2.js"
    - name: "app1-min"
      minify: true
      module: Main
      outfile: "app/main-app.min.js"
    - name: "app2-min"
      minify: true
      module: MainAlt1
      outfile: "app/alt-app1.min.js"
    - name: "app3-min"
      minify: true
      module: MainAlt2
      outfile: "app/alt-app2.min.js"
```

(As an aside, you could add a `mininote` Boolean field that would automatically add `.min` before `.js` in output file names when minifying)
