### ISSUE TITLE
Add `spago.yaml` to Schema Store

### ISSUE THREAD

**Issue by JordanMartinez** [purescript/spago#1144]
See https://www.schemastore.org/json/ but this would add autocomplete support in VS Code.

**Comment by cakekindel** [comment]
Would there be value in adding a json schema file in the repo? ex.

`/spago.yaml.schema.json`
```json
{
  "type": "object",
  "properties": {
    "workspace": ..
    ...
  }
}
```

It would add a little maintenance burden, since changing the schema in code would also have to be reflected in the schema file, but could add the autocomplete immediately for people who want to add something like this to their spago.yaml:

```yaml
# yaml-language-server: $schema=https://github.com/purescript/spago/master/spago.yaml.schema.json
workspace:
  buildOpts:
    censorLibraryWarnings: all
  packageSet:
    registry: 58.0.0
```
