### ISSUE TITLE
Spago accepts packages without `spago.yaml` from registry but not local

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1149]
This package does not have a `spago.yaml` file https://github.com/thomashoneyman/purescript-halogen-store/tree/v0.5.4 but `spago` can still use it from the registry. When i download the package local and add this to my `spago.yaml`

```yaml
workspace:
  extra_packages:
    halogen-store:
      path: ./purescript-halogen-store
```

I get this error
```
❌ Could not read config at ./purescript-halogen-store
Error: Did not find purescript-halogen-store/spago.yaml file.
```
