### ISSUE TITLE
suggested spago install command does not work

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1176]
```
Sources for package 'foldable-traversable-extra' import the following transitive dependencies - please add them to the project dependencies, or remove the imports:
  arrays
    from `Data.Foldable.Extra`, which imports:
      Data.Array
      Data.Array.NonEmpty
  partial
    from `Data.Foldable.Extra`, which imports:
      Partial.Unsafe

These errors can be fixed by running the below command(s):
spago install -p foldable-traversable-extra arrays partial
```

Correct command was: `spago install arrays partial`

Using registry, not package-sets

**Comment by f-f** [comment]
Both commands should work, can you provide more details on how this doesn't work?

**Comment by flip111** [comment]
```
» spago install -p arrays
Reading Spago workspace configuration...

❌ Selected package arrays was not found in the local packages.
Available packages:
  foldable-traversable-extra
```

```yaml
package:
  name: foldable-traversable-extra
  dependencies:
    - arrays
    - either: ">=6.1.0 <7.0.0"
    - foldable-traversable: ">=6.0.0 <7.0.0"
    - maybe: ">=6.0.0 <7.0.0"
    - ordered-collections: ">=3.1.1 <4.0.0"
    - partial: ">=4.0.0 <5.0.0"
    - prelude: ">=6.0.1 <7.0.0"
    - transformers: ">=6.0.0 <7.0.0"
    - tuples: ">=7.0.0 <8.0.0"
  publish:
    version: 0.0.4
    license: Apache-2.0
    location:
      githubOwner: flip111
      githubRepo: foldable-traversable-extra
workspace:
  extra_packages: {}
  package_set:
    registry: 48.4.0
```

```
» spago install arrays
Reading Spago workspace configuration...

✅ Selecting package to build: foldable-traversable-extra

⚠️ You tried to install some packages that are already present in the configuration, proceeding anyways:
  - arrays
Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.
```

**Comment by flip111** [comment]
second scenario

```yaml
package:
  name: foldable-traversable-extra
  dependencies:
    - either: ">=6.1.0 <7.0.0"
    - foldable-traversable: ">=6.0.0 <7.0.0"
    - maybe: ">=6.0.0 <7.0.0"
    - ordered-collections: ">=3.1.1 <4.0.0"
    - partial: ">=4.0.0 <5.0.0"
    - prelude: ">=6.0.1 <7.0.0"
    - transformers: ">=6.0.0 <7.0.0"
    - tuples: ">=7.0.0 <8.0.0"
  publish:
    version: 0.0.4
    license: Apache-2.0
    location:
      githubOwner: flip111
      githubRepo: foldable-traversable-extra
workspace:
  extra_packages: {}
  package_set:
    registry: 48.4.0
```

```
» spago install -p arrays
Reading Spago workspace configuration...

❌ Selected package arrays was not found in the local packages.
Available packages:
  foldable-traversable-extra
```

```
» spago install arrays
Reading Spago workspace configuration...

✅ Selecting package to build: foldable-traversable-extra

Adding 1 package to the config in spago.yaml
Lockfile is out of date (installing new packages), generating it...
Lockfile written to spago.lock. Please commit this file.
Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.
```

**Comment by flip111** [comment]
third scenario

```yaml
package:
  name: foldable-traversable-extra
  dependencies:
    - either: ">=6.1.0 <7.0.0"
    - foldable-traversable: ">=6.0.0 <7.0.0"
    - maybe: ">=6.0.0 <7.0.0"
    - ordered-collections: ">=3.1.1 <4.0.0"
    - partial: ">=4.0.0 <5.0.0"
    - prelude: ">=6.0.1 <7.0.0"
    - transformers: ">=6.0.0 <7.0.0"
    - tuples: ">=7.0.0 <8.0.0"
  publish:
    version: 0.0.4
    license: Apache-2.0
    location:
      githubOwner: flip111
      githubRepo: foldable-traversable-extra
workspace:
  extra_packages: {}
  package_set:
    registry: 48.4.0
```

```
rm -rf output/Data.Array
rm -rf .spago/packages/arrays-7.2.1
```

```
» spago install -p arrays
Reading Spago workspace configuration...

❌ Selected package arrays was not found in the local packages.
Available packages:
  foldable-traversable-extra
```

```
» spago install arrays
Reading Spago workspace configuration...

✅ Selecting package to build: foldable-traversable-extra

Adding 1 package to the config in spago.yaml
Lockfile is out of date (installing new packages), generating it...
Lockfile written to spago.lock. Please commit this file.
Downloading dependencies...
Building...
[1 of 4] Compiling Data.Array
[3 of 4] Compiling Data.Array.Partial
[2 of 4] Compiling Data.Array.NonEmpty
[4 of 4] Compiling Data.Set.NonEmpty
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.
```
