### ISSUE TITLE
`verbose-stats` showing improper stats

### ISSUE THREAD

**Issue by imsaravana369** [purescript/spago#1195]
When there are no errors/warnings(on rebuild also since we are  not stashing warnings), verbose-stats is showing empty stats whereas `compact-stats` is working fine
 ```yaml
 workspace:
   build_opts:
     stat_verbosity: "verbose-stats"
```
<img width="470" alt="Screenshot 2024-03-08 at 01 06 46" src="https://github.com/purescript/spago/assets/61308886/c97cc99d-f470-4280-885d-7c0a58d75ca2">
