### ISSUE TITLE
How to run benchmarks?

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1205]
I have this repo https://github.com/flip111/purescript-sequences/tree/cd85e2818c55e5e0905a034fdec7b138042517eb
Tried to run benchmarks like so

```
» spago run --main Benchmark.Main
Reading Spago workspace configuration...

✅ Selecting package to build: sequences

Downloading dependencies...
Building...
           Src   Lib   All
Warnings     0     0     0
Errors       0     0     0

✅ Build succeeded.


❌ Running failed.
Module Benchmark.Main not found! Are you including it in your build?
```

Also tried to modify [this](https://github.com/flip111/purescript-sequences/blob/master/spago.yaml#L23) to this

```yaml
workspace:
  extra_packages:
    benchmark:
      path: benchmarks
  package_set:
    registry: 50.4.0
```

same error appears
