### ISSUE TITLE
Error when adding custom `location`

### ISSUE THREAD

**Issue by CGenie** [purescript/spago#1217]
So I have this yaml:
```yaml
workspace:
  publish:
    location:
      git: https://gitlab.iscpif.fr/gargantext/purescript-address-rfc2821
```
When I try `spago build` it throws me this error:
```
❌ Couldn't parse Spago config, error:
  An error occurred while decoding a JSON value:
  Under 'Config':
  At object key package:
  Under 'PackageConfig':
  At object key publish:
  Under 'PublishConfig':
  At object key location:
  Under 'GitHub':
  At object key githubRepo:
  No value was found.
The configuration file help can be found here https://github.com/purescript/sp
```
I have spago 0.93.29.

The README isn't very specific about this. I see `git://....` mentioned, but `https` should be fine as well? And erroring about missing `githubOwner`/`githubRepo` seems that these fields are required anyways.
