### ISSUE TITLE
Feature request: spago.local.yaml overrider

### ISSUE THREAD

**Issue by srghma** [purescript/spago#1265]
# Problem

For example, I work on https://github.com/mikesol/purescript-deku/blob/main/spago.yaml locally

And 

it has

```yaml
workspace:
  extraPackages:
    package1:
      git: ...
      ref: ...
    package2:
      repo: ...
      version: ...
      dependencies: ...
```

But I have package1 and package2 locally, and I want to use them, so, I have to override

```yaml
workspace:
  extraPackages:
    package1:
      # git: ...
      # ref: ...
      path: ...
    package2:
      # repo: ...
      # version: ...
      # dependencies: ...
      path: ...
```

But when I need to commit - I have to revert changes to version1

And I have many more repos like purescript-deku where I do the same THUS tedious

# Solution

1. To have a file `spago.local.yaml` near `spago.yaml`

```yaml
workspace:
  extraPackages:
    package1:
      path: ...
    package2:
      path: ...
```

2. I would add this file to global gitignore

3. Teach spago to merge these two files in memory
