### ISSUE TITLE
Pedantic packages flag ignoring local packages

### ISSUE THREAD

**Issue by onslaughtq** [purescript/spago#1281]
With the latest version of spago, 0.93.39, we are having an issue with using pedantic packages. It is reporting that packages, which are defined in the same repo are not needed.

Our setup is 
```
- packageA
|  -- src/
| -- spago.yaml (with a workspace section)
- packageB
| -- src/
| -- spago.yaml (also with a workspace section)
```

Our `packageA` lists `packageB` as a dependency in the `package` section and also includes a reference to `packageB` as an extra package in the workspace, i.e.

```
package:
  dependcies:
    -packageB
workspace:
  extraPackages:
    packageB:
      path: ../packageB
```

With this setup, packageB is now being listed as unused, even though it is definitely used by package A.
