### ISSUE TITLE
add `authors: [...]` field to spago.yaml `package.publish` ?

### ISSUE THREAD

**Issue by srghma** [purescript/spago#1294]
some bower.json have authors field

```
{
  "name": "purescript-nullable",
  "authors": [
    "Phil Freeman <paf31@cantab.net>"
  ],
  "description": "A library for dealing with nulls",
  "license": "MIT",
  "repository": {
    "type": "git",
    "url": "https://github.com/purescript-contrib/purescript-nullable.git"
  },
  "ignore": [
    "**/.*",
    "bower_components",
    "node_modules",
    "output",
    "bower.json",
    "package.json"
  ]
}
```

mabye add this field to spago.yaml too?

```
package:
  name: nullable
  description: A library for dealing with nulls
  authors:
    - Phil Freeman <paf31@cantab.net>
```

```
Reading Spago workspace configuration...

✘ Couldn't parse Spago config, error:


  $.package: Unknown field(s): authors
```
