### ISSUE TITLE
Cannot publish a project that is referenced by other projects in the workspace

### ISSUE THREAD

**Issue by fsoikin** [purescript/spago#1307]
When checking dependencies, `spago publish` checks dependencies of _all_ packages in the workspace, not just the one being published.

The culprit line is: https://github.com/purescript/spago/blob/5407217903328b05b5fed2ddeed4076f66727491/src/Spago/Command/Publish.purs#L120

It smooshes all dependencies in a single bucket before checking them.

### ./spago.yaml
```
package: 
  name: project-a
  publish: ...
workspace:
  ...
```

### ./b/spago.yaml
```
package: 
  name: project-b
  dependencies:
    - project-a
```

### Try to publish:
```
> spago publish -p project-a

Your package "project-a" is not ready for publishing yet, encountered 1 error:

✘ Some of the packages you specified as `extraPackages` do not point to the Registry.
To be able to publish a package to the registry, all of its dependencies have to be packages registered on the Registry.
Please replace the following packages with versions that are present in the Registry:
  - project-a
```
