### ISSUE TITLE
Use local package (instead of override local package??)

### ISSUE THREAD

**Issue by flip111** [purescript/spago#1338]
https://github.com/purescript/spago?tab=readme-ov-file#override-a-package-in-the-package-set-with-a-local-one

I have these files

./purescript-tidy/spago.yaml
```yaml
package:
  name: tidy
  description: A syntax tidy-upper (formatter) for PureScript.
  publish:
    version: 0.11.1
    license: MIT
    location:
      githubOwner: natefaubion
      githubRepo: purescript-tidy
  build:
    strict: true
  dependencies:
    - arrays: ">=7.3.0 <8.0.0"
    - control: ">=6.0.0 <7.0.0"
    - dodo-printer: ">=2.2.3 <3.0.0"
    - either: ">=6.1.0 <7.0.0"
    - foldable-traversable: ">=6.0.0 <7.0.0"
    - language-cst-parser: ">=0.14.1 <0.15.0"
    - lists: ">=7.0.0 <8.0.0"
    - maybe: ">=6.0.0 <7.0.0"
    - newtype: ">=5.0.0 <6.0.0"
    - ordered-collections: ">=3.2.0 <4.0.0"
    - partial: ">=4.0.0 <5.0.0"
    - prelude: ">=6.0.1 <7.0.0"
    - strings: ">=6.0.1 <7.0.0"
    - tuples: ">=7.0.0 <8.0.0"
    - debug
    - foreign
  test:
    main: Test.Main
    dependencies:
      - argparse-basic
      - node-fs
      - node-glob-basic
      - node-path
      - tidy-bin: "*"
workspace:
  extraPackages:
    language-cst-parser:
      path: ../purescript-language-cst-parser
```

./purescript-language-cst-parser/spago.yaml
```yaml
package:
  name: language-cst-parser
  description: PureScript CST Parser written in PureScript 
  publish:
    version: 0.14.1
    license: MIT
    location:
      githubOwner: natefaubion
      githubRepo: purescript-language-cst-parser
  build:
    strict: true
  dependencies:
    - arrays
    - console
    - const
    - control
    - effect
    - either
    - enums
    - foldable-traversable
    - free
    - functions
    - functors
    - identity
    - integers
    - lazy
    - lists
    - maybe
    - newtype
    - node-process
    - numbers
    - ordered-collections
    - partial
    - prelude
    - st
    - strings
    - transformers
    - tuples
    - typelevel-prelude
    - unfoldable
    - unsafe-coerce
  test:
    main: Test.Main
    dependencies: []
workspace:
  extraPackages: {}
  packageSet:
    registry: 64.6.0
```

when i compile the first package i get this error
```
Reading Spago workspace configuration...

✓ Selecting package to build: tidy-bin

Refreshing the Registry Index...

✘ Could not solve the package dependencies, errors:
  No versions found in the registry for language-cst-parser in range
  >=0.14.1 seen in tidy-bin@0.0.0
  <0.15.0 seen in tidy-bin@0.0.0
```

when i remove the version constraint part `: ">=0.14.1 <0.15.0"` the error stays the same.

Does this feature work in such a way that a package has to be in the registry first before you can use it as local package? Meaning a true "override" and not just "use local package"? It would be nice if one could use local packages without them being in the registry.

**Comment by smilack** [comment]
I think the problem is that `tidy-bin` is a separate package, contained in `tidy`, and it's a dependency of `tidy` but it also depends on `language-cst-parser`.

I was able to get it to build with these changes:

`./purescript-tidy/spago.yaml`
- Remove version dependency for `language-cst-parser`
- Add `language-cst-parser` and `tidy-bin` to `extraPackages`:
  ```yaml
  workspace:
    extraPackages:
      language-cst-parser:
        path: ../purescript-language-cst-parser
      tidy-bin:
        path: bin
  ```
`./purescript-tidy/bin/spago.yaml`
- Remove version dependency for `language-cst-parser`
- Add `language-cst-parser` to `extraPackages`:
  ```yaml
  workspace:
    extraPackages:
      language-cst-parser:
        path: ../../purescript-language-cst-parser
  ```
