### ISSUE TITLE
Question: How to migrate specs from old dhall to yaml on spago@next

### ISSUE THREAD

**Issue by hedefalk** [purescript/spago#969]
Hi,

I have this .spec.dhall:

```
let conf = ./spago.dhall

in conf // {
  sources = conf.sources # [ "test/**/*.purs" ],
  dependencies = conf.dependencies # [ "spec", "spec-discovery", "effect", "aff", "control", "either" ]
}
```

And I'm trying to understand how to correctly migrate to the yaml format for spago@next. The test field lets me specify extra library deps but not sources? Is this instead hardwired to "src" and "test/spec"?

I now ran the migrate command on spago classic to get a yaml for my main spago.dhall. Then I added a test block to the package:

```yaml
  test:
    main: Test.Main
    dependencies:
      - spec
      - spec-discovery
      - effect
      - aff
      - control
      - either
```

and I needed to state this is a module or it would complain on no main() exported:

```yaml
  bundle:
    type: module
```

So my full yaml now is:

```yaml
package:
  name: kb-parsers
  dependencies:
    - foldable-traversable
    - integers
    - maybe
    - numbers
    - parsing
    - prelude
    - string-parsers
    - strings
    - tuples
  bundle:
    type: module
  test:
    main: Test.Main
    dependencies:
      - spec
      - spec-discovery
      - effect
      - aff
      - control
      - either

workspace:
  extra_packages: {}
  package_set:
    url: https://raw.githubusercontent.com/purescript/package-sets/psc-0.15.9-20230619/packages.json
    hash: sha256-fasqPSTP+iHLBxmgt294mT40HnUOnvLK1ZMiyJJGhu4=
```

And both spago test and spago bundle now works. The only thing I'm wondering about is the fact that I haven't clearly separated spec sources from main sources like before - the bundle previously didn't even have access to the spec sources but now they might do?

Or is this a non-issue with minification?
