### ISSUE TITLE
build with "plan from the solver" fails after successful normal build.

### ISSUE THREAD

**Issue by thought2** [purescript/spago#978]
I'm trying to publish a package, I ran `spago fetch --ensure-ranges`  and then `spago publish`. It builds the package successfully. But then it builds again  'with the build plan from the solver' and the build fails. (https://github.com/thought2/purescript-chameleon-react-basic/tree/v0.0.1)
I could publish the package successfully via the "GH issue workflow" though.

*spago.yaml:*
```
package:
  dependencies:
    - arrays: ">=7.2.1 <8.0.0"
    - chameleon: ">=0.0.3 <0.0.4"
    - effect: ">=4.0.0 <5.0.0"
    - foreign: ">=7.0.0 <8.0.0"
    - foreign-object: ">=4.1.0 <5.0.0"
    - maybe: ">=6.0.0 <7.0.0"
    - prelude: ">=6.0.1 <7.0.0"
    - react-basic: ">=17.0.0 <18.0.0"
    - react-basic-dom: ">=6.1.0 <7.0.0"
    - react-basic-hooks: ">=8.2.0 <9.0.0"
    - strings: ">=6.0.1 <7.0.0"
    - tuples: ">=7.0.0 <8.0.0"
    - unsafe-coerce: ">=6.0.0 <7.0.0"
    - web-dom: ">=6.0.0 <7.0.0"
  name: chameleon-react-basic
  test:
    dependencies: []
    main: Test.Main

  publish:
    version: 0.0.1
    license: BSD-3-Clause
    location:
      githubOwner: thought2
      githubRepo: purescript-chameleon-react-basic

workspace:
  extra_packages: {}
  package_set:
    registry: 31.1.0
  build_opts:
    pedantic_packages: true
```

*CLI output:*
```
(...)
           Src   Lib   All
Warnings     9     0     9
Errors       0     0     0

✅ Build succeeded.

Looking for unused and undeclared transitive dependencies...
Building again with the build plan from the solver...
Building...
purs compile: No files found using pattern: .spago/packages/indexed-monad-2.1.0/src/**/*.purs
[1/5 ModuleNotFound] .spago/packages/react-basic-hooks-8.2.0/src/React/Basic/Hooks/Internal.purs:16:1

  16  import Control.Applicative.Indexed (class IxApplicative)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Control.Applicative.Indexed was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[2/5 ModuleNotFound] .spago/packages/react-basic-hooks-8.2.0/src/React/Basic/Hooks/Internal.purs:17:1

  17  import Control.Apply.Indexed (class IxApply)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Control.Apply.Indexed was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[3/5 ModuleNotFound] .spago/packages/react-basic-hooks-8.2.0/src/React/Basic/Hooks/Internal.purs:18:1

  18  import Control.Bind.Indexed (class IxBind, ibind)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Control.Bind.Indexed was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[4/5 ModuleNotFound] .spago/packages/react-basic-hooks-8.2.0/src/React/Basic/Hooks/Internal.purs:19:1

  19  import Control.Monad.Indexed (class IxMonad)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Control.Monad.Indexed was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[5/5 ModuleNotFound] .spago/packages/react-basic-hooks-8.2.0/src/React/Basic/Hooks/Internal.purs:20:1

  20  import Data.Functor.Indexed (class IxFunctor)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Data.Functor.Indexed was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

           Src   Lib   All
Warnings     0     0     0
Errors       5     0     5

❌ Failed to build.
```
